# Generated by Django 4.0.4 on 2022-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('presence', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
