# Generated by Django 4.0.4 on 2022-05-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0002_alter_tickets_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'managed': False, 'verbose_name': 'Billet', 'verbose_name_plural': 'Billets'},
        ),
    ]
