# Generated by Django 4.0.4 on 2022-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(blank=True, max_length=50, null=True)),
                ('unitary_cost', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'purchases',
                'managed': False,
            },
        ),
    ]
