# Generated by Django 4.0.4 on 2022-05-31 18:51

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('name_club', models.CharField(max_length=50, unique=True, verbose_name='Nom club')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalClubs',
            fields=[
                ('id_club', models.IntegerField(blank=True, db_index=True)),
                ('name_club', models.CharField(db_index=True, max_length=50, verbose_name='Nom club')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Club',
                'verbose_name_plural': 'historical Clubs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
