# Generated by Django 4.0.4 on 2022-05-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('name_club', models.CharField(max_length=50, unique=True, verbose_name='Nom club')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
