# Generated by Django 4.0.4 on 2022-05-31 19:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('name_event', models.CharField(max_length=50, unique=True, verbose_name='Nom événement')),
                ('date_event', models.DateField(blank=True, null=True, verbose_name='Date événement')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Durée événement')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True,
                                               verbose_name='Budget événement (sponsors + administration)')),
                ('available_places', models.IntegerField(blank=True, null=True, verbose_name='Places disponibles')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True,
                                                     verbose_name='Prix billet')),
            ],
            options={
                'verbose_name': 'Evénement',
                'verbose_name_plural': 'Evénements',
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvents',
            fields=[
                ('id_event', models.IntegerField(blank=True, db_index=True)),
                ('name_event', models.CharField(db_index=True, max_length=50, verbose_name='Nom événement')),
                ('date_event', models.DateField(blank=True, null=True, verbose_name='Date événement')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Durée événement')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True,
                                               verbose_name='Budget événement (sponsors + administration)')),
                ('available_places', models.IntegerField(blank=True, null=True, verbose_name='Places disponibles')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True,
                                                     verbose_name='Prix billet')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('club', models.ForeignKey(blank=True, db_column='club', db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                           to='clubs.clubs', verbose_name='Club organisateur')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Evénement',
                'verbose_name_plural': 'historical Evénements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
