# Generated by Django 4.0.4 on 2022-05-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_alter_events_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False, 'verbose_name': 'Evénement', 'verbose_name_plural': 'Evénements'},
        ),
    ]
