# Generated by Django 4.0.4 on 2022-05-31 19:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(blank=True, max_length=50, null=True, verbose_name='article')),
                ('unitary_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True,
                                                     verbose_name='Coût unitaire')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Date achat')),
                ('invoice_number',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de facture')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'db_table': 'purchases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchases',
            fields=[
                ('id_purchase', models.IntegerField(blank=True, db_index=True)),
                ('article', models.CharField(blank=True, max_length=50, null=True, verbose_name='article')),
                ('unitary_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True,
                                                     verbose_name='Coût unitaire')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Date achat')),
                ('invoice_number',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de facture')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('id_club', models.ForeignKey(blank=True, db_column='id_club', db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                              to='clubs.clubs', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'historical Achat',
                'verbose_name_plural': 'historical Achats',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
