# Generated by Django 4.0.4 on 2022-05-31 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('evenements', '0001_initial'),
        ('achats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchases',
            name='id_event',
            field=models.ForeignKey(blank=True, db_column='id_event', db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='evenements.events', verbose_name='Evénement'),
        ),
        migrations.AddField(
            model_name='historicalpurchases',
            name='owner_obj',
            field=models.ForeignKey(blank=True, db_column='owner_obj', db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
