# Generated by Django 4.0.4 on 2022-05-31 19:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('name_student', models.CharField(max_length=25, verbose_name='Nom étudiant')),
                ('surname_student', models.CharField(max_length=25, verbose_name='Prénom')),
                ('study_field', models.CharField(blank=True, choices=[('Sciences de la santé', 'Sciences de la santé'),
                                                                      ('Ingénierie', 'Ingénierie'),
                                                                      ('Business School', 'Business School'),
                                                                      ('Droit', 'Droit'), ('Management en hôtellerie',
                                                                                           'Management en hôtellerie')],
                                                 max_length=50, null=True, verbose_name='Specialité')),
                ('email', models.CharField(blank=True, max_length=35, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudents',
            fields=[
                ('id_student', models.IntegerField(blank=True, db_index=True)),
                ('name_student', models.CharField(max_length=25, verbose_name='Nom étudiant')),
                ('surname_student', models.CharField(max_length=25, verbose_name='Prénom')),
                ('study_field', models.CharField(blank=True, choices=[('Sciences de la santé', 'Sciences de la santé'),
                                                                      ('Ingénierie', 'Ingénierie'),
                                                                      ('Business School', 'Business School'),
                                                                      ('Droit', 'Droit'), ('Management en hôtellerie',
                                                                                           'Management en hôtellerie')],
                                                 max_length=50, null=True, verbose_name='Specialité')),
                ('email', models.CharField(blank=True, max_length=35, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Etudiant',
                'verbose_name_plural': 'historical Etudiants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
