# Generated by Django 4.0.4 on 2022-05-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False, 'verbose_name_plural': 'Students'},
        ),
    ]
