# Generated by Django 4.0.4 on 2022-05-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False, 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
    ]
