# Generated by Django 4.0.4 on 2022-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id_label', models.AutoField(primary_key=True, serialize=False)),
                ('name_label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'label',
                'managed': False,
            },
        ),
    ]
